# Continuous Delivery
name: test-schedule-deploy
run-name: CD pipeline scheduled deployments

on:
  schedule:
    - cron: '55 19 * * 1,2,3,4,5'  # Daily run for Canary deployments
    - cron: '55 19 * * 1'          # Weekly run for Production deployments
    - cron: '55 23 * * *'          # Test
    - cron: '05 00 * * *'          # Test 2

jobs:

  # Scheduled dispatch to deploy Stage (Test)
  dispatch-deploy-stage:
    name: Dispatch
    if: github.event.schedule == '05 00 * * *'
    uses: ./.github/workflows/test-cd.yml
    with: 
      target-ref: 'main'
      deploy-deploy: 'stg'
