# Continuous Delivery
name: test-schedule-deploy
run-name: CD pipeline scheduled deployments

on:
  schedule:
    - cron: '55 19 * * 1,2,3,4,5'  # Daily run for Canary deployments
    - cron: '55 19 * * 1'          # Weekly run for Production deployments
    - cron: '55 23 * * *'          # Test
    - cron: '08 03 * * *'          # Test 2

  workflow_dispatch:
    inputs:
      target-ref:
        description: 'Tag or Main'
        required: true
        default: 'main'
        type: string
      deploy-target:
        description: 'Deployment target'
        required: true
        default: 'stg'
        type: choice
        options:
        - stg
        - can
        - prd

jobs:

  # Scheduled dispatch to deploy Stage (Test)
  dispatch-deploy-stage:
    name: Dispatch
    #if: github.event.schedule == '08 03 * * *'
    uses: ./.github/workflows/test-cd.yml
    with: 
      target-ref: 'main'
      deploy-target: 'stg'
