# Continuous Deployment Workflow for Stage
name: DEPLOY-TO-STAGE
run-name: Continuous deployment triggered for Stage Environment

on:
  # Runs on pushes targeting the default branch
  repository_dispatch:
    types: [deploy]

jobs: 

  # Continuous delivery workflow in 'ss-pipeline' repo
  continuous-delivery:
    name: CD
    uses: dr3dr3/ss-pipeline/.github/workflows/continuous-delivery.yml@main
    with: 
      target-ref: 'main'
      deploy-target: 'stg'
    permissions:
      pages: write
      id-token: write
    secrets: inherit