# Continuous Deployment Workflow for Stage
name: DEPLOY-TO-STAGE
run-name: Continuous deployment triggered for Stage Environment

on:
  # Runs on pushes targeting the default branch
  repository_dispatch:
    types: [deploy]

jobs:

  # Build static site using Reveal-MD
  build-stg:
    name: Build STG
    if: ${{ !github.event.client_payload.paused }}
    uses: dr3dr3/devops-demo/.github/workflows/build-revealmd.yml@main
    with: 
      target-ref: ${{ github.event.client_payload.target_ref }}
      deploy-target: 'stg'
    secrets: inherit

  # Deploy to GitHub Pages on the Stage Repo
  deploy-to-github-pages:
    name: Deploy GHP(STG)
    needs: build-stg
    uses: dr3dr3/devops-demo/.github/workflows/deploy-github-pages.yml@main
    permissions:
      contents: read
      pages: write
      id-token: write
    with:
      target-ref: ${{ github.event.client_payload.target_ref }}
      artefact-ref: ${{ github.event.client_payload.target_ref }}      
      deploy-target: 'stg'
    secrets: inherit