name: DEPLOY-TO-STAGE
run-name: Continuous Deployment for Stage Environment

on:
  # Runs on pushes targeting the default branch
  repository_dispatch:
    types: [deploy]

jobs: 

  # Continuous delivery workflow in 'ss-pipeline' repo
  continuous-delivery:
    name: CD
    uses: dr3dr3/ss-pipeline/.github/workflows/continuous-delivery.yml@main
    with: 
      from-soln: ${{ github.event.client_payload.trigger }}
      target-ref: ${{ github.event.client_payload.target-ref }}
      #target-deploy: 'stg'
    permissions:
      contents: read
      pages: write
      id-token: write
    secrets: inherit